### ISSUE TITLE
floating point error in encoding

### ISSUE THREAD

**Issue by satarupaguha11** [ryankiros/skip-thoughts#24]
I have successfully trained skipthoughts from scratch on my own data. Now given new data X, I want to get its vectors representation. So i do the following
    vectors = skipthoughts.encode(model, X)
But this gives me the following error:
    floating point exception (core dumped)

I have also set the THEANO_FLAGS floatX to float32.
Any help will be appreciated.

**Comment by lovekesh-thakur** [comment]
Not an expert but most likely you're getting memory issues. 
i think you are running out of memory.

**Comment by polyrhythmatic** [comment]
Having the same issue on a GTX Titan X and 32 gigs of ram with a rather small sentence corpus (around 37k sentences). Any idea what the problem could be? I'm not getting any information on the error.

**Comment by polyrhythmatic** [comment]
ah - updated this to use just 100 sentences and it seems to work. I'll have to see the maximum I can set this to.

**Comment by clovercoser** [comment]
X should be a list, not string. You may forget  '[ ]'.

**Comment by pcallier** [comment]
We got this behavior sometimes from inadvertantly sending in empty strings (after overzealous preprocessing). It was always hard to pinpoint so we're not sure we fixed it but that might be something to check.

**Comment by Spider101** [comment]
I got the same error. Turns out one of the sentences in the list was just whitespace, i.e. `" "`. So, after the internal preprocessing in the skipthoughts.py script, it came up to be an empty string which might have been the reason for the error. Hope this helps!

**Comment by pavanpankaj** [comment]
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    vectors=encoder.encode(sent_tok)
  File "/local_home/rpr/code/skipthoughts.py", line 102, in encode
    return encode(self._model, X, use_norm, verbose, batch_size, use_eos)
  File "/local_home/rpr/code/skipthoughts.py", line 132, in encode
    for minibatch in range(numbatches):

please help me

**Comment by pavanpankaj** [comment]
3
128
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    vectors=encoder.encode(sent_tok)
  File "/local_home/rpr/code/skipthoughts.py", line 102, in encode
    return encode(self._model, X, use_norm, verbose, batch_size, use_eos)
  File "/local_home/rpr/code/skipthoughts.py", line 132, in encode
    for minibatch in range(numbatches):


I thought only 3 words in dictionary are found. In batches it is going on and the batch size is 128. only 3 in a batch found so 3/128 is float range(float) is an error it is showing
