### ISSUE TITLE
Facing problem in implementing decoding using skip-thoughts vector.

### ISSUE THREAD

**Issue by ChokshiUtsav** [ryankiros/skip-thoughts#50]
Hello,
I am facing problem in implementing decoding using skip-thoughts vector.
I am getting following error while running decoder.py

```
Loading model parameters...
Compiling encoders...
Loading tables...
Packing up...
10
{'grad_clip': 5.0, 'dim': 1600, 'optimizer': 'adam', 'dim_word': 620, 'dictionary': '/home/utsav/skip-thoughts/dict', 'decay_c': 0.0, 'reload_': False, 'n_words': 18, 'batch_size': 1, 'encoder': 'gru', 'maxlen_w': 10, 'saveto': '/home/utsav/skip-thoughts/saved_models/sample.npz', 'embeddings': None, 'decoder': 'gru', 'sampleFreq': 1, 'max_epochs': 20, 'dispFreq': 1, 'dimctx': 4800, 'doutput': False, 'saveFreq': 1}
Loading dictionary...
Building model
Building sampler
Building f_init... Building f_next.. Done
Building f_log_probs... Done
Building f_cost... Done
Done
Building f_grad... Building optimizers... Optimization
Epoch  0
OK
Traceback (most recent call last):
  File "decoder.py", line 21, in <module>
    train.trainer(X,X,encoder)
  File "/home/utsav/skip-thoughts/decoding/train.py", line 180, in trainer
    x, mask, ctx = homogeneous_data.prepare_data(x, c, worddict, stmodel, maxlen=maxlen_w, n_words=n_words)
  File "/home/utsav/skip-thoughts/decoding/homogeneous_data.py", line 109, in prepare_data
    feat_list = skipthoughts.encode(model, feat_list, use_eos=False, verbose=False)
  File "/home/utsav/skip-thoughts/skipthoughts.py", line 115, in encode
    for w in model['utable'].keys():
TypeError: 'Encoder' object has no attribute '__getitem__'


```
Decoder.py :
-----------------
```
import sys
sys.path.append('/home/utsav/skip-thoughts')
import skipthoughts
import nltk
import vocab
import train

model = skipthoughts.load_model()
encoder = skipthoughts.Encoder(model)

f = open('../sample.txt','r')
sentences = [nltk.word_tokenize(r.lower()) for r in f.readlines()]
X = [' '.join(s) for s in sentences]

worddict, wordcount = vocab.build_dictionary(X)

print len(worddict)

vocab.save_dictionary(worddict, wordcount, '/home/utsav/skip-thoughts/dict')

train.trainer(X,X,encoder)

```

Train.py :
-----------
```
# main trainer
def trainer(X, C, stmodel,
            dimctx=4800, #vector dimensionality
            dim_word=620, # word vector dimensionality
            dim=1600, # the number of GRU units
            encoder='gru',
            decoder='gru',
            doutput=False,
            max_epochs=20,
            dispFreq=1,
            decay_c=0.,
            grad_clip=5.,
            n_words=10,
            maxlen_w=10,
            optimizer='adam',
            batch_size = 1,
            saveto='/home/utsav/skip-thoughts/saved_models/sample.npz',
            dictionary='/home/utsav/skip-thoughts/dict',
            embeddings=None,
            saveFreq=1,
            sampleFreq=1,
            reload_=False):
```

Here is my training text :

```
He is a good person.
He is a good person.
I am a serious guy.
I am a serious guy.
He is a good person.
He is a good person.
I am a serious guy.
I am a serious guy.
```

**Comment by ChokshiUtsav** [comment]
This Issue is resolved.
I changed last line of decoder.py to : 
`train.trainer(X,X,model)
`
I guess, README.md for decoding should mention that encoder model is the one returned by 
`skipthoughts.load_model()`

**Comment by afrozas** [comment]
@ChokshiUtsav 
How much RAM should I have at hand to train decoder on ~10000 sentences? (just an estimate)
On just 10 sentences, 16 GB of RAM is exhausted and the decoder is still at Packing Up step. Any help would be appreciated. Thanks!
