### ISSUE TITLE
KeyError in decoding

### ISSUE THREAD

**Issue by shavakagrawal** [ryankiros/skip-thoughts#61]
Upon running the load_model function in the decoding package with both the uni_skip and bi_skip models provided, I get the following error:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "tools.py", line 47, in load_model`
`    params = init_params(options)`
`  File "model.py", line 27, in init_params`
`    params = get_layer('ff')[0](options, params, prefix='ff_state', nin=options['dimctx'], nout=options['dim'])`
`KeyError: 'dimctx'`

Even after I attempt to hard code the value of dimctx, the gru_cond_simple throws a similar error.

**Comment by afrozas** [comment]
@shavakagrawal 
Were you able to run the decoder? I am also facing the same error!

I found an interface for skip-thought vectors [here](https://github.com/danielricks/penseur), but now the memory requirement seems to be a major issue. Can you help me with how much RAM is required for the decoder on ~10000 sentences, if you were able to run the decoder? Thanks!

**Comment by shavakagrawal** [comment]
Nope, ended up retraining on my corpus
