### ISSUE TITLE
I have a problem "UnicodeDecodeError"  on python3

### ISSUE THREAD

**Issue by AlphaWill0** [ryankiros/skip-thoughts#66]
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\format.py", line 637, in read_array
    array = pickle.load(fp, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_loader.py", line 111, in <module>
    main()
  File "data_loader.py", line 106, in main
    save_caption_vectors_flowers(args.data_dir)
  File "data_loader.py", line 77, in save_caption_vectors_flowers
    model = skipthoughts.load_model()
  File "G:\postgradute_learn\01code\text-to-image-master\skipthoughts.py", line 64, in load_model
    utable, btable = load_tables()
  File "G:\postgradute_learn\01code\text-to-image-master\skipthoughts.py", line 85, in load_tables
    utable = numpy.load(path_to_tables + 'utable.npy')
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 406, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\format.py", line 643, in read_array
    "to numpy.load" % (err,))
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'z\xb2J=\xb1W!=\xe9\x9d\x07\xbdg\xfa\x89\xbd\xc2\x0b\xcd\xbd\xbb\xa5\x84\xbc\xb4\xab5=S\xa0\x84<\x82d\x13=\xd8q\xed<\xfd\
x02\x92<\xe6E\x14=-}\x08<G\xfa\x9f\xbd\x12\x93\x01;r\x81\x93\xbdhwU\xbdL\x98!\xbd\xca\x89\xdd\xbaN1\x85=@\x04\xbb=VA\xbe\xbd\xfb(\x02>\xa9\x07\x92\xbdJ<\x8f=\'\xadW<\xea\xf2\xe9<\xe7\x1d\xc9\xbc\x06\
x13*\xbd\xf2\x07]=\xf7\x9c==\xa13U=\x13\xc4(\xbd\xf6X\x03\xbcT\x1e\xfc;\xe0\xad\xbf=A*(\xbd\xad\xc7\xa2\xbb\xc8\x0f\x07\xbdKC\x14\xbd\x9f\x01\xd1<+w\xe0=\x0b\x95\x9f=OZ\x00=\xd5\xfa\n<\xb2\x81a\xbd\x
1cB\x80=\xb7\'\x8a=\x01\x0f\x13\xbb(\xfb\x97=\xc4\x9c\'<\xc8x\xb3\xbc8{(\xbd\x82r\x96<\xb5\xf4l\xbd\x03*\xad\xbdl\xda\xf0\xbb\xbd\x91\x9f\xbaK\xc4\xd2=\x8cz\x0e=\xc5\x10\xb1=\xea\x0c\xd7;\xaft\x8d=\x
e42\x00\xbe\x06\xa2\x98=\x16\x02r\xbd4\xc7?=\xd6Y?\xbc\xf4]\x15\xbd\xd2D\x95\xbc\n\xf2\x1e="\xce\xea<\x89u]\xbd\x1b\x97\x86\xbc4\xee\t>2%\xc8\xbdE\xf5}\xbd\xa9h\x18=\x05\x15\x8c\xbc}\xc5a\xbd%\xe8\x9
9=\xdf\x06\xc2\xbb!G]\xbb\xa7o\xca;Oen<n`\xa8<\xc7\x00\xa1=0\xde\xa2\xbd#OI=g$9=\xe0\xf2\x07\xbd\xd31\\\xbc\x8c\x93\x97\xbc\x1d\x94\t\xbcI\x1bg\xbd\xd2\x19\x85=\xc4\xb0\xbf\xbc\xe8\x9bq\xbc\xae/\x8e\
xbc\xe8\x01\xc5<\xaa\xbb\x83=4\xf0J\xbd\x9e\x19!\xbdw\x14o=\xb5\xf1\xdc\xbciS\x8a;\xd3\xa7\xce\xbd\xce\x16N\xbd+\xde\x12;lh+\xbd\x87b\x84\xbc\xc2\x91\x0e\xbd\x8e\x7fe\xbdNs\x92<kr\xaf=tv>\xbd\xf1\xa1
\xe7<\xff@\xdd\xbdv\xbbn\xbb\xe8?F\xbde\xc0Q\xbc\x13r\xd8\xbdl\xaf\xb3\xbb\xe0.!<&L]<\xab\xf2?=\xb6P3\xbd\xdc\x8e\r<\xa85:\xbb\xfd\x16\x1e=6-\xc2=\xaa\xe8N\xbc\xd1c\x9f\xbd\x95\xacl\xbd@\x9a\x81\xbd\
x8f\x02\x8f=pC\x9e;!4:\xbc+_\x9f\xbd\xad\xa4\x92=\xd9\x1fz<jy\x92\xbd\x12\x9dj\xbd\x81\x05\xda\xbd\xban\x9b<e\x8c9\xbd\x1b!\xc0<\xf1\xf4\xbb\xbdb\xa9g\xbc\x8d\x8c+\xbdKj\xca<\x82\x81\xee<\x98O\x90\xb
c/\x8f\xee\xbc\x15\x1eU=\xfboh;\xfd\x19\xb5=\xc2\xfa/\xbd\xfa\x07\xd5\xbc\x07\xbb\x98\xbd<c\xb3<VV =*\xbdb\xbd\x11-k<\xa48z\xbcWy\x90\xbd\xb7\xec\xb1=_\xe4\xe7;\x1a\x93\xc2\xbc\x19\x92\xc8<\xd2\xb6P\
xbc\xc1\xc8\xfe\xbc\xd1\xe4c\xbc\xbd\xbe\xba\xbb\x12\xf6C=d5\x13;\xb7\xd9\x92=\xb0\xacV<\xbb\xa5\x0f\xbc\xcc\xbf3<N\x92\xdf<p\xe2\x11\xbb\x1cb+\xbd\xb2\xd1p\xbdK\xa0M\xbc\xbc\xed4\xbd\xa8\xa7\xb9<H\x
02\xad\xbc\x7fv\x90<\xdb\xc1\n=B-\xe4<\xb5\xbep\xbd\x87\xac7<\xb7e\xa7\xbbj\x98\xf9<\x07\xa8\x13\xbc\x81\xfc\x8d\xbd\x97\x83\xa1\xbdE\xd9\x88\xbdsO$=\x1es%=\x9d9\xc6\xbc1\xd9%=\x10\xfc\xc5\xbb\xe6RC\
xbd\x98/\xb9\xbb`\xa3\xcc<M\xb7\xaf\xbc\xbc\xbd\x85\xbd\x84x\x1c\xbd\x06\x19s\xbc\xed\x0b\xa3\xbc\x10@\x01\xbd\x80\x95W=!\x94\xbf<\x1e\x04,<\nTR=\x0f\xedt\xbc\xdf\xd0\x89=\xe8\x0b3;BQ\x0f\xbdA\xe4\xd
c<\x08\xce\xab\xbd\xfa\xe5>=\x83\xe3\x82\xbd\x97\xb3\xb2=\x8d\x14\xd1\xbc\xbb?\xe8<\xb7\xa23\xbd\x15S\xe2=\x17!\x11<\x06\xb2\xc4\xbc*\x9b&>\xa5\nF\xbcw+f<\xb4\xebE=\xdch-\xbd\x07q\x81\xbd8i,\xbd\xf2v
\x8a<\x1et\xb7;I\x9c\xf4<\xcd\rg\xbd\x94r\x98\xbdw\xe7I=\xa34)=(\xa1\x08\xbe\x10 \x0c\xbb,5\x82<\x01x\x13\xbd\x17\x8eg\xbb\n\x12\xdd\xbc2B\xeb\xbd\x18\xe0\xca={\xde5=\x14\xa7Z;\x1e\xf8\xd3=\xc4\x17\x
f6<\xd2%!:l\xa3\xc7=8\xa3\x0e=c\xe5\x14\xbd\x1e\xf4l=\xd2\x10\x05>\xdbr\x1a<\xbfA\xfd\xbd4C\xac\xbb\x86\xbe\xd3\xbc\xd0\x8b\x11\xbd\xa2\x9a\xab\xbc/hN\xbd\x13\x08\x1a\xbdTfv=u\xf7[=\xa4\x1e\x1e\xbd\x
9b\xa5q\xbd4w\xed<U\t\x9a\xbc\xfb\xd3\xa5<\xda\xce\x98\xba\xe0C8=t\xfa\x04\xbc\xbe\xdf\xf5\xbc\xb7\xbf\x00<\xef\x92\xd5:\xda\x05\x8f\xbd\xc4D\xaa=21\xbb\xbc\x92\x80\x8c=\x04\xef\x8b\xba\x1d!\xf5<\xc1
\xcb\xe1\xbc\xca\x17*=\xdd\x16\xfd<SP0\xbd\x88>\xb1\xbd&\xb95<\xfb\x15\xa6\xbc<\x19"\xbcO\x7f\x0e\xbc\x95\xd6.=l\x15\x87<G]\xd0;#}\xc1\xbb5\\_\xbb\xc4\x8a\x87=1\xd8\x8f=C\x06\xea;\xbb\xbd\xde=4\xb1\x
0f\xbd\xa8\xfc\xd9\xbc&\xcf\xb3=\xe5\x99\x0e\xbdA{\xa1\xbd$[I=\xdc\x0c\xdf<E\x10s=*\xd5\xff<\xfcr\xb1\xbc/\xea7\xbc!\x8f9\xbdH\x14\n=\xf5\x7f\xfe<\xbf\xe9\t=a#\xf6=x\xf9\xc6:\xd9\n\xc1\xbcp*\xbd\xbd\
xfc\xc9z=\xcd\x07/\xbc8\x97\xb1\xbdJ?\xb5=\xa6\x91Z\xbd\xf1X\xd1<]\xc0\xd0\xbc\xa4B\x01=k\xa3z\xbd`\x19\x90=K\x8c\xa8:\x04\x0b\x1d;e>\xae\xbdo2\t<7\xb0\x8c\xbc\xb6\x93u=\x02\xbc\x1b\xbd\x92\xc5\xcc=\
xb5\x86\x04=\x98\xf0,\xbd\xc9?\xee<\x03\xa7\x0f=\xe3\x89f\xbc\xf2uT<\xf7\xd6\xc4\xbc\xa0\xe8\x80\xbd\r\x1c\x9a=\xc2JR<\x8dw\xab;\xda\x12+\xbdV\x11\xe8\xbc_-g=@\x0b\r=\x0e\x84\x90="z\x08<\xe2\xcb\xb5<
\x06i{=!\xb6\x16<)*\x0e=\x1f\x80b\xbd\x8b\xcb==\xe9\x11q=\xd4)&<\xf8\xb0\x07\xbdM\x17B\xbbo3\xfb\xbc\x0fJ\x94<\x8f:\xbb<^m\xc8\xbc\xba\x8b\xa5\xbcJ\x93\xa2\xbc\xc1f\x81<\xcf\x0e\x08=KoO\xbd\xd0,\x96\
xbd!\xd4\x95\xbcz\xf6\x8f=\xab!\x85<\xc8\xdf;\xbb\xffr\x9b=\x8e\xcfP\xbd\xfa\x05o;\xf2fc\xbd4u"\xbc\x99\xd35\xbd\xe3\xed\'\xbd1\xd4\x06\xbd\xcaT\xf1\xbc\x02?\x89=D~Z\xbcX\x8e\xd5\xbc\xd3\xf3\x86\xbd|
\xc8U\xba\xb9\x1co=s\xa5-\xbd)\xdc\x9b\xbd\xe5\x84{<O\x03^\xbc\xb5\xb5\x8a=\xc5\xd9`\xbc\x95\xbe\x14=\x1d\x84\xda\xbc\x1d4\xf0=\xab\xf28;\xc3\'C\xbdDo\xab\xbb\x05\x8c\xba<\x8bG\x05=R\xae\xbb;\x98\xbd
Q<\x9f\x9a\xc3\xbc\xf0\xf3(=\x92\x15]<\x17\xa0\x9b\xbd\xa4\xdd\x8c\xbdk#\xfb:\xc9\xfcl=\xbe\x94=\xbc\x1e\x03\x18\xbd\x12\xf9\xff;\x91\x98\x86\xbck\xc6H\xbcA\xb6u\xbcy\x0c\xef<\x14D?=\x17L^<\x1b\x06f\
xbd\x80\x8f0\xbd\xcfg\xab<\x8f\xf9\xcd<\xae\xe8><\xb7\x13\x04\xbd\x94f\x86\xbb\xf9q{\xbd\x9a\xef\xb6\xbb|\xb6\xb0\xba\x17\xe4\xb5=\xe7\x9c\xd6= 8\xec\xbcp\xf9\xef\xbcG5\x7f=r+z\xbd \x9b\xc2;H[)\xbd\x
d8,R<\x9c\xb2\xa9\xbc~\x80s\xbd\xad\xb7\xbe\xbd\nq\xb0\xbdk\x84\x12\xbd \x98\xc5\xbb\x1c\x98\x84<+lM;\xcaX\x91\xbd\xbb)\x84\xbdc\x1aQ\xbc\xa0w\x15\xbbH#\xa7\xbd\xffD\x8a\xbd\xac\xf8\xb6<\x85\xce\xa7\
xbc\x13\xdb\xf0;\xdb$\x02\xbe\xce*6=\xab\xb5&\xbdh\xaa\x1e\xbd\x12\xa5K\xbdR\xb1s\xbbf\r/\xbd\x06U\x08:\xfb\xc8\xa0\xbcl\x80\xcf\xbd\x18nH=F\xc0Z\xbd\xa6T\x92\xbd\x7fl\x1d\xbd\x81i"=\x05+\x01\xbd\xda
n\xf5:#\xe6\x8b\xbd\xf19\x16\xbcl\xdf\xa7<\xc6\xd5\x11<}\x1eJ\xba\x98K\xf7<\x105\xb7<\x1c\xbd\x9a\xbbde\xa0\xbd\xec\x13\xc6\xbc=\xccU=\xd9\xc7\xe3=\x98NK<\xfd\xab\x94\xbdI\xd4;<&\xfe\xe6\xbc\x1b#7=*\
xcb\xde\xbc\x9etN\xb9U\xfc\x98\xbc\xd9\x1f\x99\xbb\xea+o=e\x84\xaf\xbc\x98\xd7\r;L2@\xbd\x0b\xbc\xa6=\x9f\x1fJ\xbd\xe0\x15\xf9\xba\xb0\x1f7=v\xc4_=?\x10\x01\xbd\x08-5\xbd\x0fVA\xbd\x8e\xa0+=\xbf\x93\
'=\xe6\x12E=\xb9\xc3)=\xfby\\<c5/\xbd\x19\xf0[\xbcW\xe9\xb7\xbd\x00\xbe\xcf\xbdX\xdf:=\xdbF\xa4=\xfc\x16[;\xa4 .\xb9\x99\x18\x19\xbd\x91\xdcD\xbd\x02D\x07:\xa7\xff_<\xff\x0f\x85<Z\xe7%\xbd\x87{\x98=\
x02|0=S\xad\xa6\xbb\x98\xba\x86\xbd\xaf\x925=\xc5\x03\xe8<Y\xc5|=\x80>\t\xbd\xb9B\x00\xbd\xb4\xe6c\xbb\x8c\x97\x9d\xbc\x9cEF<\xf4G\xfe\xbd\xc7jN=T\xc4\xef\xbcy\xb9\xbd\xbd5\xbb\t=\xf8\x16\x82\xbd\xbb
\xdcy\xbd\x1b\xd5\xfa<\xb9\xb7 ;\x90\xd7\xe7<\x93\xa1\xd9=\xb7\xc2/\xbdN/\x8c=\x0b\xb4\'<\n\x93g<\xb3\xe3j\xbdg\xd2\x07<:\xf1g;\x10\xc9\xbd\xbcAH\x88=\x99W\x13=Jh\x96\xbd2\xb8a\xbd\'\x87,==M\xc9\xbd\
xf7e\x88\xbcy\xc9\x96\xbd\xa0\x843\xbdJo\x9e\xbd\xb0\xb1O\xbd{{?=\x8eg\x14;\xe3\xdd\x0f\xbd\x87UX;\xb5\x83R\xbd\xce\x84\xa5\xbc\x94@==\x00\xbd\x0f\xbdz\xea\xe2\xbc\xe9.{\xbc\x7f\x9e\xf3\xbc\xc5\x1fT=
\xb3Wt=&\xb9\xd0<y\xf9/=\x8er\xa2\xbb\x85k#<#<\x1a\xbd\x18"I\xbd\x81\x1c\xbd=M\xbb\x9d<cM\xfe\xbc@\xa2/\xbb\xd2\x8b\xf7\xbc\xcd{\xa7\xbbxDC\xbc\xccL\x199n\xb8P\xbc\x94\x06D=E*\x85=\x82\xadZ=L\xea(\xb
c0\xc0D\xbd\x82\xcf\x80\xbcH\xa7\x98\xbc\xb2\x81[\xbdX\'b=\xebC}\xbd\x1c\xe9Y;', 1, 2, 'ordinal not in range(128)')
You may need to pass the encoding= option to numpy.load

I modify  "import cPickle as pkl"  to "import pickle as pkl".
Now, I have this problem. Can you help me solve this problem?

**Comment by AlphaWill0** [comment]
Create a separate .py  with  np.load('skipthoughts/models/btable.npy',encoding='latin1') to open，but  i can not open btable.npy.

this error,
EOFError: Ran out of input

**Comment by hrushikeshjadhav9** [comment]
**I am experiencing the  same problem.
Did you get it right?**


/Users/hrushikeshjadhav/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
Starting to encode...
Loading pre-trained models...
Loading model parameters...
Compiling encoders...
Loading tables...
Traceback (most recent call last):
  File "/Users/hrushikeshjadhav/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 657, in read_array
    array = pickle.load(fp, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 1: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edd.py", line 116, in <module>
    summary = summarize()
  File "edd.py", line 97, in summarize
    enc_sentences = skipthought_encode(sentences)
  File "edd.py", line 73, in skipthought_encode
    model = skipthoughts.load_model()
  File "/Users/hrushikeshjadhav/Documents/eddProject/skipthoughts.py", line 59, in load_model
    utable, btable = load_tables()
  File "/Users/hrushikeshjadhav/Documents/eddProject/skipthoughts.py", line 79, in load_tables
    utable = numpy.load(path_to_tables + 'utable.npy')
  File "/Users/hrushikeshjadhav/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "/Users/hrushikeshjadhav/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 663, in read_array
    "to numpy.load" % (err,))
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'z\xb2J=\xb1W!=\xe9\x9d\x07\xbdg\xfa\x89\xbd\xc2\x0b\xcd\xbd\xbb\xa5\x84\xbc\xb4\xab5=S\xa0\x84<\x82d\x13=\xd8q\xed<\xfd\x02\x92<\xe6E\x14=-}\x08<G\xfa\x9f\xbd\x12\x93\x01;r\x81\x93\xbdhwU\xbdL\x98!\xbd\xca\x89\xdd\xbaN1\x85=@\x04\xbb=VA\xbe\xbd\xfb(\x02>\xa9\x07\x92\xbdJ<\x8f=\'\xadW<\xea\xf2\xe9<\xe7\x1d\xc9\xbc\x06\x13*\xbd\xf2\x07]=\xf7\x9c==\xa13U=\x13\xc4(\xbd\xf6X\x03\xbcT\x1e\xfc;\xe0\xad\xbf=A*(\xbd\xad\xc7\xa2\xbb\xc8\x0f\x07\xbdKC\x14\xbd\x9f\x01\xd1<+w\xe0=\x0b\x95\x9f=OZ\x00=\xd5\xfa\n<\xb2\x81a\xbd\x1cB\x80=\xb7\'\x8a=\x01\x0f\x13\xbb(\xfb\x97=\xc4\x9c\'<\xc8x\xb3\xbc8{(\xbd\x82r\x96<\xb5\xf4l\xbd\x03*\xad\xbdl\xda\xf0\xbb\xbd\x91\x9f\xbaK\xc4\xd2=\x8cz\x0e=\xc5\x10\xb1=\xea\x0c\xd7;\xaft\x8d=\xe42\x00\xbe\x06\xa2\x98=\x16\x02r\xbd4\xc7?=\xd6Y?\xbc\xf4]\x15\xbd\xd2D\x95\xbc\n\xf2\x1e="\xce\xea<\x89u]\xbd\x1b\x97\x86\xbc4\xee\t>2%\xc8\xbdE\xf5}\xbd\xa9h\x18=\x05\x15\x8c\xbc}\xc5a\xbd%\xe8\x99=\xdf\x06\xc2\xbb!G]\xbb\xa7o\xca;Oen<n`\xa8<\xc7\x00\xa1=0\xde\xa2\xbd#OI=g$9=\xe0\xf2\x07\xbd\xd31\\\xbc\x8c\x93\x97\xbc\x1d\x94\t\xbcI\x1bg\xbd\xd2\x19\x85=\xc4\xb0\xbf\xbc\xe8\x9bq\xbc\xae/\x8e\xbc\xe8\x01\xc5<\xaa\xbb\x83=4\xf0J\xbd\x9e\x19!\xbdw\x14o=\xb5\xf1\xdc\xbciS\x8a;\xd3\xa7\xce\xbd\xce\x16N\xbd+\xde\x12;lh+\xbd\x87b\x84\xbc\xc2\x91\x0e\xbd\x8e\x7fe\xbdNs\x92<kr\xaf=tv>\xbd\xf1\xa1\xe7<\xff@\xdd\xbdv\xbbn\xbb\xe8?F\xbde\xc0Q\xbc\x13r\xd8\xbdl\xaf\xb3\xbb\xe0.!<&L]<\xab\xf2?=\xb6P3\xbd\xdc\x8e\r<\xa85:\xbb\xfd\x16\x1e=6-\xc2=\xaa\xe8N\xbc\xd1c\x9f\xbd\x95\xacl\xbd@\x9a\x81\xbd\x8f\x02\x8f=pC\x9e;!4:\xbc+_\x9f\xbd\xad\xa4\x92=\xd9\x1fz<jy\x92\xbd\x12\x9dj\xbd\x81\x05\xda\xbd\xban\x9b<e\x8c9\xbd\x1b!\xc0<\xf1\xf4\xbb\xbdb\xa9g\xbc\x8d\x8c+\xbdKj\xca<\x82\x81\xee<\x98O\x90\xbc/\x8f\xee\xbc\x15\x1eU=\xfboh;\xfd\x19\xb5=\xc2\xfa/\xbd\xfa\x07\xd5\xbc\x07\xbb\x98\xbd<c\xb3<VV =*\xbdb\xbd\x11-k<\xa48z\xbcWy\x90\xbd\xb7\xec\xb1=_\xe4\xe7;\x1a\x93\xc2\xbc\x19\x92\xc8<\xd2\xb6P\xbc\xc1\xc8\xfe\xbc\xd1\xe4c\xbc\xbd\xbe\xba\xbb\x12\xf6C=d5\x13;\xb7\xd9\x92=\xb0\xacV<\xbb\xa5\x0f\xbc\xcc\xbf3<N\x92\xdf<p\xe2\x11\xbb\x1cb+\xbd\xb2\xd1p\xbdK\xa0M\xbc\xbc\xed4\xbd\xa8\xa7\xb9<H\x02\xad\xbc\x7fv\x90<\xdb\xc1\n=B-\xe4<\xb5\xbep\xbd\x87\xac7<\xb7e\xa7\xbbj\x98\xf9<\x07\xa8\x13\xbc\x81\xfc\x8d\xbd\x97\x83\xa1\xbdE\xd9\x88\xbdsO$=\x1es%=\x9d9\xc6\xbc1\xd9%=\x10\xfc\xc5\xbb\xe6RC\xbd\x98/\xb9\xbb`\xa3\xcc<M\xb7\xaf\xbc\xbc\xbd\x85\xbd\x84x\x1c\xbd\x06\x19s\xbc\xed\x0b\xa3\xbc\x10@\x01\xbd\x80\x95W=!\x94\xbf<\x1e\x04,<\nTR=\x0f\xedt\xbc\xdf\xd0\x89=\xe8\x0b3;BQ\x0f\xbdA\xe4\xdc<\x08\xce\xab\xbd\xfa\xe5>=\x83\xe3\x82\xbd\x97\xb3\xb2=\x8d\x14\xd1\xbc\xbb?\xe8<\xb7\xa23\xbd\x15S\xe2=\x17!\x11<\x06\xb2\xc4\xbc*\x9b&>\xa5\nF\xbcw+f<\xb4\xebE=\xdch-\xbd\x07q\x81\xbd8i,\xbd\xf2v\x8a<\x1et\xb7;I\x9c\xf4<\xcd\rg\xbd\x94r\x98\xbdw\xe7I=\xa34)=(\xa1\x08\xbe\x10 \x0c\xbb,5\x82<\x01x\x13\xbd\x17\x8eg\xbb\n\x12\xdd\xbc2B\xeb\xbd\x18\xe0\xca={\xde5=\x14\xa7Z;\x1e\xf8\xd3=\xc4\x17\xf6<\xd2%!:l\xa3\xc7=8\xa3\x0e=c\xe5\x14\xbd\x1e\xf4l=\xd2\x10\x05>\xdbr\x1a<\xbfA\xfd\xbd4C\xac\xbb\x86\xbe\xd3\xbc\xd0\x8b\x11\xbd\xa2\x9a\xab\xbc/hN\xbd\x13\x08\x1a\xbdTfv=u\xf7[=\xa4\x1e\x1e\xbd\x9b\xa5q\xbd4w\xed<U\t\x9a\xbc\xfb\xd3\xa5<\xda\xce\x98\xba\xe0C8=t\xfa\x04\xbc\xbe\xdf\xf5\xbc\xb7\xbf\x00<\xef\x92\xd5:\xda\x05\x8f\xbd\xc4D\xaa=21\xbb\xbc\x92\x80\x8c=\x04\xef\x8b\xba\x1d!\xf5<\xc1\xcb\xe1\xbc\xca\x17*=\xdd\x16\xfd<SP0\xbd\x88>\xb1\xbd&\xb95<\xfb\x15\xa6\xbc<\x19"\xbcO\x7f\x0e\xbc\x95\xd6.=l\x15\x87<G]\xd0;#}\xc1\xbb5\\_\xbb\xc4\x8a\x87=1\xd8\x8f=C\x06\xea;\xbb\xbd\xde=4\xb1\x0f\xbd\xa8\xfc\xd9\xbc&\xcf\xb3=\xe5\x99\x0e\xbdA{\xa1\xbd$[I=\xdc\x0c\xdf<E\x10s=*\xd5\xff<\xfcr\xb1\xbc/\xea7\xbc!\x8f9\xbdH\x14\n=\xf5\x7f\xfe<\xbf\xe9\t=a#\xf6=x\xf9\xc6:\xd9\n\xc1\xbcp*\xbd\xbd\xfc\xc9z=\xcd\x07/\xbc8\x97\xb1\xbdJ?\xb5=\xa6\x91Z\xbd\xf1X\xd1<]\xc0\xd0\xbc\xa4B\x01=k\xa3z\xbd`\x19\x90=K\x8c\xa8:\x04\x0b\x1d;e>\xae\xbdo2\t<7\xb0\x8c\xbc\xb6\x93u=\x02\xbc\x1b\xbd\x92\xc5\xcc=\xb5\x86\x04=\x98\xf0,\xbd\xc9?\xee<\x03\xa7\x0f=\xe3\x89f\xbc\xf2uT<\xf7\xd6\xc4\xbc\xa0\xe8\x80\xbd\r\x1c\x9a=\xc2JR<\x8dw\xab;\xda\x12+\xbdV\x11\xe8\xbc_-g=@\x0b\r=\x0e\x84\x90="z\x08<\xe2\xcb\xb5<\x06i{=!\xb6\x16<)*\x0e=\x1f\x80b\xbd\x8b\xcb==\xe9\x11q=\xd4)&<\xf8\xb0\x07\xbdM\x17B\xbbo3\xfb\xbc\x0fJ\x94<\x8f:\xbb<^m\xc8\xbc\xba\x8b\xa5\xbcJ\x93\xa2\xbc\xc1f\x81<\xcf\x0e\x08=KoO\xbd\xd0,\x96\xbd!\xd4\x95\xbcz\xf6\x8f=\xab!\x85<\xc8\xdf;\xbb\xffr\x9b=\x8e\xcfP\xbd\xfa\x05o;\xf2fc\xbd4u"\xbc\x99\xd35\xbd\xe3\xed\'\xbd1\xd4\x06\xbd\xcaT\xf1\xbc\x02?\x89=D~Z\xbcX\x8e\xd5\xbc\xd3\xf3\x86\xbd|\xc8U\xba\xb9\x1co=s\xa5-\xbd)\xdc\x9b\xbd\xe5\x84{<O\x03^\xbc\xb5\xb5\x8a=\xc5\xd9`\xbc\x95\xbe\x14=\x1d\x84\xda\xbc\x1d4\xf0=\xab\xf28;\xc3\'C\xbdDo\xab\xbb\x05\x8c\xba<\x8bG\x05=R\xae\xbb;\x98\xbdQ<\x9f\x9a\xc3\xbc\xf0\xf3(=\x92\x15]<\x17\xa0\x9b\xbd\xa4\xdd\x8c\xbdk#\xfb:\xc9\xfcl=\xbe\x94=\xbc\x1e\x03\x18\xbd\x12\xf9\xff;\x91\x98\x86\xbck\xc6H\xbcA\xb6u\xbcy\x0c\xef<\x14D?=\x17L^<\x1b\x06f\xbd\x80\x8f0\xbd\xcfg\xab<\x8f\xf9\xcd<\xae\xe8><\xb7\x13\x04\xbd\x94f\x86\xbb\xf9q{\xbd\x9a\xef\xb6\xbb|\xb6\xb0\xba\x17\xe4\xb5=\xe7\x9c\xd6= 8\xec\xbcp\xf9\xef\xbcG5\x7f=r+z\xbd \x9b\xc2;H[)\xbd\xd8,R<\x9c\xb2\xa9\xbc~\x80s\xbd\xad\xb7\xbe\xbd\nq\xb0\xbdk\x84\x12\xbd \x98\xc5\xbb\x1c\x98\x84<+lM;\xcaX\x91\xbd\xbb)\x84\xbdc\x1aQ\xbc\xa0w\x15\xbbH#\xa7\xbd\xffD\x8a\xbd\xac\xf8\xb6<\x85\xce\xa7\xbc\x13\xdb\xf0;\xdb$\x02\xbe\xce*6=\xab\xb5&\xbdh\xaa\x1e\xbd\x12\xa5K\xbdR\xb1s\xbbf\r/\xbd\x06U\x08:\xfb\xc8\xa0\xbcl\x80\xcf\xbd\x18nH=F\xc0Z\xbd\xa6T\x92\xbd\x7fl\x1d\xbd\x81i"=\x05+\x01\xbd\xdan\xf5:#\xe6\x8b\xbd\xf19\x16\xbcl\xdf\xa7<\xc6\xd5\x11<}\x1eJ\xba\x98K\xf7<\x105\xb7<\x1c\xbd\x9a\xbbde\xa0\xbd\xec\x13\xc6\xbc=\xccU=\xd9\xc7\xe3=\x98NK<\xfd\xab\x94\xbdI\xd4;<&\xfe\xe6\xbc\x1b#7=*\xcb\xde\xbc\x9etN\xb9U\xfc\x98\xbc\xd9\x1f\x99\xbb\xea+o=e\x84\xaf\xbc\x98\xd7\r;L2@\xbd\x0b\xbc\xa6=\x9f\x1fJ\xbd\xe0\x15\xf9\xba\xb0\x1f7=v\xc4_=?\x10\x01\xbd\x08-5\xbd\x0fVA\xbd\x8e\xa0+=\xbf\x93\'=\xe6\x12E=\xb9\xc3)=\xfby\\<c5/\xbd\x19\xf0[\xbcW\xe9\xb7\xbd\x00\xbe\xcf\xbdX\xdf:=\xdbF\xa4=\xfc\x16[;\xa4 .\xb9\x99\x18\x19\xbd\x91\xdcD\xbd\x02D\x07:\xa7\xff_<\xff\x0f\x85<Z\xe7%\xbd\x87{\x98=\x02|0=S\xad\xa6\xbb\x98\xba\x86\xbd\xaf\x925=\xc5\x03\xe8<Y\xc5|=\x80>\t\xbd\xb9B\x00\xbd\xb4\xe6c\xbb\x8c\x97\x9d\xbc\x9cEF<\xf4G\xfe\xbd\xc7jN=T\xc4\xef\xbcy\xb9\xbd\xbd5\xbb\t=\xf8\x16\x82\xbd\xbb\xdcy\xbd\x1b\xd5\xfa<\xb9\xb7 ;\x90\xd7\xe7<\x93\xa1\xd9=\xb7\xc2/\xbdN/\x8c=\x0b\xb4\'<\n\x93g<\xb3\xe3j\xbdg\xd2\x07<:\xf1g;\x10\xc9\xbd\xbcAH\x88=\x99W\x13=Jh\x96\xbd2\xb8a\xbd\'\x87,==M\xc9\xbd\xf7e\x88\xbcy\xc9\x96\xbd\xa0\x843\xbdJo\x9e\xbd\xb0\xb1O\xbd{{?=\x8eg\x14;\xe3\xdd\x0f\xbd\x87UX;\xb5\x83R\xbd\xce\x84\xa5\xbc\x94@==\x00\xbd\x0f\xbdz\xea\xe2\xbc\xe9.{\xbc\x7f\x9e\xf3\xbc\xc5\x1fT=\xb3Wt=&\xb9\xd0<y\xf9/=\x8er\xa2\xbb\x85k#<#<\x1a\xbd\x18"I\xbd\x81\x1c\xbd=M\xbb\x9d<cM\xfe\xbc@\xa2/\xbb\xd2\x8b\xf7\xbc\xcd{\xa7\xbbxDC\xbc\xccL\x199n\xb8P\xbc\x94\x06D=E*\x85=\x82\xadZ=L\xea(\xbc0\xc0D\xbd\x82\xcf\x80\xbcH\xa7\x98\xbc\xb2\x81[\xbdX\'b=\xebC}\xbd\x1c\xe9Y;', 1, 2, 'ordinal not in range(128)')
You may need to pass the encoding= option to numpy.load

**Comment by ellivalla** [comment]
To solve the problem you have to add the paramater encoding = 'latin1' to numpy.load()
The default encoding in Python 2 is ascii and in Python 3 it is utf-8. latin1 (a.k.a., ISO-8859-1) is a superset of ascii and it should work.
