### ISSUE TITLE
EOF Error when loading tables

### ISSUE THREAD

**Issue by nd-z** [ryankiros/skip-thoughts#68]
When trying to load the model using `skipthoughts.load_model()`, I encountered the following error and I am unsure as to how to resolve it.

```
Loading model parameters...
Compiling encoders...
Loading tables...
Traceback (most recent call last):
line 80, in load_tables
    btable = numpy.load(path_to_tables + 'btable.npy')
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 419, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/format.py", line 640, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError

```

**Comment by echelon-debug** [comment]
I'm encountering this same issue. Did you find a solution?

**Comment by RohanBolusani** [comment]
> I'm encountering this same issue. Did you find a solution?

hey any solution??
