### ISSUE TITLE
ValueError: could not broadcast input array from shape (3600) into shape (2400)

### ISSUE THREAD

**Issue by susheelkumar0077** [ryankiros/skip-thoughts#76]
Hello everyone,
I am trying to execute this code and got stuck here please can anyone help me out..

Traceback (most recent call last):
  File "/home/mcis-lap-25/PycharmProjects/storyteller/neural-storyteller-master/demo.py", line 3, in <module>
    generate.story(z, '/home/mcis-lap-25/Desktop/images.jpeg')
  File "/home/mcis-lap-25/PycharmProjects/storyteller/neural-storyteller-master/generate.py", line 59, in story
    svecs = skipthoughts.encode(z['stv'], sentences, verbose=False)
  File "/home/mcis-lap-25/PycharmProjects/storyteller/neural-storyteller-master/skipthoughts.py", line 135, in encode
    bfeatures[c] = bff[ind]

**Comment by zhangzy6** [comment]
I also occur the same problem.Could you tell me how to solve it ?
