### ISSUE TITLE
No module named 'nbsvm'

### ISSUE THREAD

**Issue by SharhadBashar** [ryankiros/skip-thoughts#83]
Traceback (most recent call last):
  File "/Users/Sharhad/skip_thoughts/tensorflow-models/skip_thoughts/bazel-bin/skip_thoughts/evaluate.runfiles/__main__/skip_thoughts/evaluate.py", line 37, in <module>
    from skipthoughts import eval_classification
  File "/Users/Sharhad/skip_thoughts/skipthoughts_kiros/skipthoughts/eval_classification.py", line 5, in <module>
    import nbsvm
ModuleNotFoundError: No module named 'nbsvm'

Any ideas how to fix this?

**Comment by Harshini-Gadige** [comment]
@SharhadBashar Hi, you have to install NBSVM as shown below.

pip install NBSVM==1.0
